#include <QApplication>
#include <QPalette>
#include "mainwindow.h"
#include <QtPlugin>
int main(int argc, char *argv[])
{
  QApplication a(argc, argv);

  QPalette palette = a.palette();
  palette.setColor(QPalette::Window, Qt::white);
  palette.setColor(QPalette::Base, Qt::white);
  a.setPalette(palette);

  a.setStyleSheet(
    "* {"
    "  font-family: 'Segoe UI', 'Calibri', Arial, sans-serif;"
    "  font-size: 9pt;"
    "}"
    "QPushButton {"
    "  background-color: #2f6fed;"
    "  color: white;"
    "  border: none;"
    "  border-radius: 6px;"
    "  padding: 6px 14px;"
    "  font-weight: 600;"
    "}"
    "QPushButton:hover {"
    "  background-color: #245bd1;"
    "}"
    "QPushButton:pressed {"
    "  background-color: #1c48a8;"
    "}"
    "QPushButton:disabled {"
    "  background-color: #dfe2e8;"
    "  color: #9aa0ab;"
    "}"
    "QGroupBox {"
    "  border: 1px solid #dcdfe4;"
    "  border-radius: 8px;"
    "  margin-top: 14px;"
    "  padding-top: 8px;"
    "  font-weight: 600;"
    "}"
    "QGroupBox::title {"
    "  subcontrol-origin: margin;"
    "  left: 10px;"
    "  padding: 0 6px;"
    "  color: #2f6fed;"
    "}"
    "QLineEdit, QComboBox, QSpinBox, QDoubleSpinBox {"
    "  border: 1px solid #d3d7de;"
    "  border-radius: 5px;"
    "  padding: 4px 6px;"
    "  background-color: white;"
    "}"
    "QLineEdit:focus, QComboBox:focus, QSpinBox:focus, QDoubleSpinBox:focus {"
    "  border: 1px solid #2f6fed;"
    "}"
    "QTabWidget::pane {"
    "  border: 1px solid #dcdfe4;"
    "  border-radius: 8px;"
    "  top: -1px;"
    "}"
    "QTabBar::tab {"
    "  background-color: #eef0f3;"
    "  color: #565d6b;"
    "  border: 1px solid #dcdfe4;"
    "  border-bottom: none;"
    "  border-top-left-radius: 8px;"
    "  border-top-right-radius: 8px;"
    "  padding: 8px 18px;"
    "  margin-right: 2px;"
    "  font-weight: 600;"
    "}"
    "QTabBar::tab:selected {"
    "  background-color: white;"
    "  color: #2f6fed;"
    "}"
    "QTabBar::tab:hover {"
    "  color: #2f6fed;"
    "}"
    "QMenuBar {"
    "  background-color: white;"
    "  border-bottom: 1px solid #dcdfe4;"
    "}"
    "QMenuBar::item:selected {"
    "  background-color: #e7edfd;"
    "  border-radius: 4px;"
    "}"
    "QMenu {"
    "  background-color: white;"
    "  border: 1px solid #dcdfe4;"
    "}"
    "QMenu::item:selected {"
    "  background-color: #2f6fed;"
    "  color: white;"
    "}"
    "QTableWidget, QTableView {"
    "  gridline-color: #eceef2;"
    "  border: 1px solid #dcdfe4;"
    "  border-radius: 6px;"
    "  background-color: white;"
    "}"
    "QHeaderView::section {"
    "  background-color: #eceef2;"
    "  color: #565d6b;"
    "  padding: 4px;"
    "  border: none;"
    "  font-weight: 600;"
    "}"
    "QScrollBar:vertical {"
    "  background: transparent;"
    "  width: 10px;"
    "}"
    "QScrollBar::handle:vertical {"
    "  background: #c7cbd4;"
    "  border-radius: 5px;"
    "  min-height: 24px;"
    "}"
    "QScrollBar:horizontal {"
    "  background: transparent;"
    "  height: 10px;"
    "}"
    "QScrollBar::handle:horizontal {"
    "  background: #c7cbd4;"
    "  border-radius: 5px;"
    "  min-width: 24px;"
    "}"
    "QToolTip {"
    "  background-color: #1f2430;"
    "  color: white;"
    "  border: none;"
    "  padding: 4px 8px;"
    "  border-radius: 4px;"
    "}"
  );

  MainWindow w;

  w.show();
  return a.exec();
}
